### ISSUE TITLE
LGPL Commercial Cost

### ISSUE THREAD

**Issue by MIDIculous** [Krasjet/imgui_juce#2]
For commercial apps what is the cost?

**Comment by Krasjet** [comment]
I'm not sure what's your use case for this library. It's intended to be used in prototyping and not production, which doesn't require any distribution so the license doesn't matter.

If you really need to distribute applications using it, LGPL should allow you to distribute the binary without releasing the source code. The catch is that any improvements to the binding between imgui and JUCE should be open or contributed back. Anything else can remain closed source. I know LGPL does have some vague requirements about static linking (you can do it, but you must allow relinking upon request). If you think it is an issue, I can add a dual license under MPL.

I guess my intention is just to prevent any party from privatizing and commercializing the prototyping stage of audio plugin development and hoping to reap a few percent of revenue share from independent developers. This is just to ensure a healthy environment for new ideas in the audio DSP community.

I don't intend to make any money from this library. If you find it saves your time in any stage of the development, just consider donate to support it.

**Comment by MIDIculous** [comment]
Ok understood...We will contact you in the future for possibly a specific license. We have no intentions of selling your code or redistributing it. We just want to use it in our Juce app.
